# Generated by Django 6.1 on 2026-08-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverages', to='insurers.branch')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('vehicle', 'Automóvel'), ('property', 'Imóvel'), ('fleet_item', 'Item de Frota'), ('travel', 'Viagem'), ('life', 'Vida'), ('business', 'Empresarial'), ('other', 'Outro')], default='other', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('approved', 'Aprovada'), ('rejected', 'Recusada'), ('converted', 'Convertida em apólice')], default='draft', max_length=20)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.branch')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client')),
                ('coverages', models.ManyToManyField(blank=True, related_name='proposals', to='policies.coverage')),
                ('covered_items', models.ManyToManyField(blank=True, related_name='proposals', to='policies.covereditem')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.insurer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
