# Generated by Django 6.1 on 2026-08-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='policies/proposals/attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='policies.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
