# Generated by Django 6.1 on 2026-08-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('insurers', '0001_initial'),
        ('policies', '0002_proposalattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.branch')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client')),
                ('coverages', models.ManyToManyField(blank=True, related_name='policies', to='policies.coverage')),
                ('covered_items', models.ManyToManyField(blank=True, related_name='policies', to='policies.covereditem')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurer')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policies.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='policies/attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='policies.policy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
