# Generated by Django 6.1 on 2026-08-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('policies', '0003_policy_policyattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('inclusion', 'Inclusão'), ('exclusion', 'Exclusão'), ('alteration', 'Alteração'), ('cancellation', 'Cancelamento'), ('other', 'Outro')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='policies.policy')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
