# Generated by Django 6.1 on 2026-08-24 13:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('policies', '0002_proposalattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='claims/attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('type', models.CharField(choices=[('collision', 'Colisão'), ('theft', 'Roubo/Furto'), ('fire', 'Incêndio'), ('flood', 'Alagamento'), ('third_party', 'Terceiro'), ('glass', 'Vidros'), ('other', 'Outro')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_analysis', 'Em análise'), ('approved', 'Aprovado'), ('paid', 'Indenizado'), ('denied', 'Recusado'), ('closed', 'Concluído')], default='open', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('covered_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.covereditem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
