# Generated by Django 6.1 on 2026-08-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('policies', '0003_policy_policyattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='claimattachment',
            name='brokerage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage'),
        ),
        migrations.AddField(
            model_name='claimattachment',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='claims.claim'),
        ),
    ]
