# Generated by Django 6.1 on 2026-08-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('policies', '0004_endorsement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('contacted', 'Contatado'), ('renewed', 'Renovado'), ('lost', 'Perdido')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='clients.client')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='policies.policy')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
