# Generated by Django 6.1 on 2026-08-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('clients', '0001_initial'),
        ('core', '0002_brokerage_user_role_user_brokerage'),
        ('insurers', '0001_initial'),
        ('policies', '0004_endorsement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('agent_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producer_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('brokerage_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga')], default='pending', max_length=20)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='agents.agent')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.brokerage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='clients.client')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='insurers.insurer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='policies.policy')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='agents.producer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
